// Generated by CoffeeScript 1.10.0
var inter;

inter = require('./interpreter');

document.addEventListener('DOMContentLoaded', function() {
  var repl, threest;
  threest = new Terminal();
  threest.setBackgroundColor("#002b36");
  threest.setTextColor("#586e75");
  threest.print("Welcome to Threest!");
  repl = function() {
    return threest.input(">", function(input) {
      inter.parse_line(input);
      inter.output.forEach(function(o) {
        return threest.print(o);
      });
      if (!inter.exited) {
        return repl();
      }
    });
  };
  repl();
  return termDiv.appendChild(threest.html);
}, false);
